### ISSUE TITLE
How to add dependency

### ISSUE THREAD

**Issue by robert2206** [ITrust/angular-xmlrpc#1]
I had put dependendy but not works.
How to add the dependency on my ionic projects?

**Comment by jchakra** [comment]
Hello robert2206 !

Actually, this project is not compatible with bower.
Did you try to add manually the 2 files (services_xmlrpc_converter.js and services_xmlrpc.js) in your _index.html_ (located within the _www/_ directory by default) after copying files in an "_www/externals_" (for instance) directory ?

__index.html__ :

    ....
    <script src="lib/ionic/js/ionic.bundle.js"></script>

    <script src="cordova.js"></script>

    <script src="externals/services_xmlrpc_converter.js"></script>
    <script src="externals/services_xmlrpc.js"></script>
    ....

Regards

**Comment by jchakra** [comment]
Hello robert2206,

A new version has been put on the repository.
A single file regroups now all the plugin code, and the angular module name changes to "_xml-rpc_".
The project has been submitted as a bower module too !

Make sure you import the js file and create a dependency in your angular application : 

    angular.module('MyApp', ['xml-rpc']);

Regards

**Comment by robert2206** [comment]
Thanks so much jchakra,
I'm adding on my project now
