### ISSUE TITLE
Update bower repo to newest version

### ISSUE THREAD

**Issue by Tympanix** [ITrust/angular-xmlrpc#5]
Bower does not contain the newest commits (e.g. i8 suppot).

**Comment by jchakra** [comment]
Thanks for notice that. I will update it asap.

**Comment by jchakra** [comment]
I made a new tagged version for the repo (1.1.0), including the work made by Tympanix (adds of unit tests and some new types), and an eslinter. Say me if it's ok for you! ;)

**Comment by Tympanix** [comment]
It's perfect. Thank you for adding my code :+1:
